project:
  type: website
  title: "Matthew Forte"

website:
  navbar:
    pinned: true
    search: true
    title: false
    left:
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "CV"
        file: Matthew_Forte_CV.pdf
      - text: "Contact"
        file: contact.qmd
    right:
      - text: IPR
        file: https://www.ipr.northwestern.edu/
      - text: STEPP Center
        file: https://steppcenter.northwestern.edu/

format:
  html:
    theme:
      - pulse
      - styles.scss
    mainfont: Work+Sans
    toc: true
    smooth-scroll: true
    anchor-sections: true

execute:
  freeze: auto